#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;

$app = new App([
    'app_path' => __DIR__ . '/app/Command',

    #Twitch
    'twitch_user' => 'your_twitch_username',
    'twitch_oauth' => 'oauth_Token'
]);

$app->setSignature("Simple chatbot.\n./chatbot twitch");
$app->runCommand($argv);
